import { z } from 'zod'

export const FormDataSchema = z.object({
  payor_label: z.string().min(1, "Jaminan / Cara Bayar haris dipilih"),
  payor_id: z.string().min(1, "Jaminan / Cara Bayar haris dipilih"),
  payor_cd: z.string().min(1, "Jaminan / Cara Bayar haris dipilih"),
  nomor_kartu: z.string(),
  nomor_sep: z.string(),
  cob_cd: z.string().optional(),
  jenis_rawat: z.number().int().refine(value => [1, 2, 3].includes(value), { message: 'Jenis rawat tidak valid' }).optional(),
  upgrade_class_ind: z.boolean().optional(),
  icu_indikator: z.boolean().optional(),
  executive_class_ind: z.boolean().optional(),
  tariff_class: z.number().int().refine(value => [1, 2, 3].includes(value), { message: 'Kelas hak tidak valid' }).optional(),
  tgl_masuk: z.date().optional(),
  tgl_pulang: z.date().optional(),
  age: z.number().int().min(0).optional(),
  cara_masuk: z.string().min(1).optional(),
  los: z.number().int().min(0).optional(),
  los_in_hour: z.string().optional(),
  birth_weight: z.number().int().min(0).optional(),
  adl_sub_acute: z.number().int().min(12).max(60).optional(),
  adl_chronic: z.number().int().min(12).max(60).optional(),
  discharge_status: z.string().optional(),
  nama_dokter: z.string().optional(),
  kode_tarif: z.string().optional(),
  jkn_sitb_checked_ind: z.boolean().optional(),
  co_insidence_ind_jkn: z.boolean().optional(),
  upgrade_class_class: z.string().optional(),
  upgrade_class_los: z.string().optional(),
  use_ind: z.boolean().optional(),
  start_dttm: z.date().optional(),
  stop_dttm: z.date().optional(),
  icu_los: z.number().int().min(0).optional(),
  tarif_poli_eks: z.number().int().min(0),

  prosedur_non_bedah: z.string().min(0).optional(),
  prosedur_bedah: z.string().min(0).optional(),
  konsultasi: z.string().min(0).optional(),
  tenaga_ahli: z.string().min(0).optional(),
  keperawatan: z.string().min(0).optional(),
  penunjang: z.string().min(0).optional(),
  radiologi: z.string().min(0).optional(),
  laboratorium: z.string().min(0).optional(),
  pelayanan_darah: z.string().min(0).optional(),
  rehabilitasi: z.string().min(0).optional(),
  kamar: z.string().min(0).optional(),
  rawat_intensif: z.string().min(0).optional(),
  obat: z.string().min(0).optional(),
  obat_kronis: z.string().min(0).optional(),
  obat_kemoterapi: z.string().min(0).optional(),
  alkes: z.string().min(0).optional(),
  bmhp: z.string().min(0).optional(),
  sewa_alat: z.string().min(0).optional(),

  sistole: z.string().min(0).optional(),
  diastole: z.string().min(0).optional(),

  diagnosa_inagrouper: z.array(z.string().refine(value => value.length > 0, { message: 'Diagnosa harus dipilih' })).optional(),
  procedure_inagrouper: z.array(z.string().refine(value => value.length > 0, { message: 'Diagnosa harus dipilih' })).optional(),

  usia_kehamilan: z.number().int().min(0).optional(),
  gravida: z.number().int().min(0).optional(),
  partus: z.number().int().min(0).optional(),
  abortus: z.number().int().min(0).optional(),
  onset_kontraksi: z.enum(['spontan', 'induksi', 'non_spontan_non_induksi']).optional(),
})